language: R

os:
- linux
- osx

r:
- release
- oldrel

cache: packages

before_install:
- wget https://cran.r-project.org/src/contrib/Archive/XML/XML_3.99-0.3.tar.gz
- R CMD INSTALL XML_3.99-0.3.tar.gz
- rm XML_3.99-0.3.tar.gz

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
  email:
    recipients:
      - n.skene@imperial.ac.uk
